[package]
name = "rust_crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
serde = {version = "1.0", features = ["derive"]}
actix-web = "3"
actix-rt = "2.4.0"
env_logger = "0.9.0"
r2d2 = "0.8.9"
r2d2_postgres = "0.18.1"