CREATE TABLE IF NOT EXISTS entities (
    entity_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text
);

INSERT INTO entities (name) VALUES ('Ivan'), ('Anton'), ('Godzilla');


CREATE TABLE IF NOT EXISTS users (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    password_hash text NOT NULL,
    enabled boolean NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    is_deleted boolean NOT NULL
);

INSERT INTO users (username, password_hash, enabled, created_at, updated_at, is_deleted)
VALUES 
    ('Ivan', '1234', TRUE, '2016-06-22 22:10:25+03', '2016-06-22 22:10:25+03', FALSE), 
    ('Anton', '1234', TRUE, '2022-06-22 22:10:25+00', '2022-06-22 22:10:25+00', FALSE), 
    ('Godzilla', '1234', TRUE, '2022-06-22 22:10:25+00', '2022-06-22 22:10:25+00', FALSE);